---
title: "mf-var data cleaning"
author: "Caleb"
date: "2022-11-18"
output: html_document
---

```{r} 
library(tidyverse) 
library(dbplyr)
library(mfbvar)
```

## Load Data Sets 


```{r}
df.q <- read.csv("mfvar/quarterly.input.correct.csv")
df.m <- read.csv("mfvar/monthly.input.mfvar.pa.csv")

df.mfvar <- full_join(df.m, df.q)

df.alpha <- df.mfvar %>% 
  select("DATE", "ur", "manemp", "rgdp", "fpi") 
```

## Log Level Growth Rates 



```{r}
library(mfbvar)

 log_diff <- function(x, lag = 1) {c(rep(NA, lag), 1200/lag * diff(log(x), lag = lag))}
 
df.alpha1 <- df.alpha %>% 
  mutate(ur = log_diff(ur), 
         manemp = log_diff(manemp), 
         rgdp = log_diff(rgdp, lag = 3), 
         fpi = log_diff(fpi, lag = 3))

# need to start with a full row and end with a full row 

df.alpha2 <- df.alpha1[-nrow(df.alpha1),]
df.alpha2 <- df.alpha2 %>%  filter(!row_number() %in% c(1, 2, 3, 4, 5))

# set the prior, freq = c(put the frequency of every variable, going to be annoying for big data sets, not sure what n_burnin and n_reps does)
prior <- set_prior(Y = df.alpha2, freq = c("m", "m", "q", "q"), n_lags = 4, n_burnin = 1000, n_reps = 1000)

# print what type of prior can be used, tells us what kind of prior can be used 
prior

a <- plot(prior)
a
```

```{r} 
# get steady state means for the prior, I think this is just for a steady state prior, but not sure how we would do this for a minnesota style prior, not sure how to get the 95% confidence intervals in r, need sample mean and then standard erorr but defintely a function that can do it for me 
# get steady state confidence intervals for steady state prior 

# get n values for each variable 
n <- colSums(!is.na(df.alpha2))
n 
# calculate confidence interval for ur 
xbar.ur <- mean(df.alpha2$ur, na.rm = t) 
n.ur <- n[2]
sd.ur <- sd(df.alpha2$ur, na.rm = T) 
margin.ur <- qt(0.975,df=n.ur-1)*sd.ur/sqrt(n.ur)

lb.ur <- xbar.ur - margin.ur 

ub.ur <- xbar.ur + margin.ur 

ci.ur <- c(lb.ur, ub.ur)

ci.ur 

# this is really wide, I think the log differences got fucked up but we're just going to run with it 


#calculate confidence intveral for manemp 
xbar.manemp <- mean(df.alpha2$manemp, na.rm = T) 
n.manemp <- n[3]
sd.manemp <- sd(df.alpha2$manemp, na.rm = T) 
margin.manemp <- qt(0.975,df=n.manemp-1)*sd.manemp/sqrt(n.manemp)

lb.manemp <- xbar.manemp - margin.manemp

ub.manemp <- xbar.manemp + margin.manemp 

ci.manemp <- c(lb.manemp, ub.manemp)

ci.manemp


# CI for rgdp 
xbar.rgdp <- mean(df.alpha2$rgdp, na.rm = T) 
n.rgdp <- n[4]
sd.rgdp <- sd(df.alpha2$rgdp, na.rm = T) 
margin.rgdp <- qt(0.975,df=n.rgdp-1)*sd.rgdp/sqrt(n.rgdp)


lb.rgdp <- xbar.rgdp - margin.rgdp

ub.rgdp <- xbar.rgdp + margin.rgdp

ci.rgdp <- c(lb.rgdp, ub.rgdp)

ci.rgdp

# CI for fpi 
xbar.fpi <- mean(df.alpha2$fpi, na.rm = T) 
n.fpi <- n[5]
sd.fpi <- sd(df.alpha2$fpi, na.rm = T) 
margin.fpi <- qt(0.975,df=n.fpi-1)*sd.fpi/sqrt(n.fpi)

lb.fpi <- xbar.fpi - margin.fpi

ub.fpi <- xbar.fpi + margin.fpi

ci.fpi <- c(lb.fpi, ub.fpi)

ci.fpi

```
## Set steady-state prior 
```{r} 
# use confidence intervals calculate up above at 95% level 
# create prior intervals 

prior_intervals <- matrix(data = c(ci.ur,
                             ci.manemp, 
                             ci.rgdp, 
                             ci.fpi), ncol = 2,byrow = TRUE)

prior_intervals1 <- matrix(data = c(-17.49642, 13.15245, 
                              -1.9974356, 0.8352119, 
                              0.2661371, 3.2123255, 
                              1.238665, 5.998560), ncol = 2, byrow = TRUE)
# not sure what this does, assume it just converts it to a useable form 
moments <- interval_to_moments(prior_intervals)

# update prior to make steady state prior 
prior1 <- update_prior(prior, d = "intercept",
                      prior_psi_mean = moments$prior_psi_mean,
                      prior_psi_Omega = moments$prior_psi_Omega)

# plot the prior to look at results, can compare to plot above with no steady state 
b <- plot(prior1)

a 
b 

# pull summary of prior 
summary(prior1)

```

## Run model without specficing prior 
```{r} 
# estimate model with steady state, ss, prior 
mod_ss_iw <- estimate_mfbvar(prior1, prior = "ss", variance = "iw")

## use predict function to view results
summary(mod_ss_iw)
 predict(mod_ss_iw, pred_bands = 0.8)
 
predict(mod_ss_iw, pred_bands = .9)
 

```

```{r} 
#plot model 
plot(mod_ss_iw)


```
``` {r} 
write.csv(df.alpha2, "C:\\Users\\brobs\\Documents\\mfvar.alpha.verison.csv")

```
